
/**
 * 所有分屏数据
 * @author lixiaodong31 2024/7/31
 * @version 1.0.0
 * @example
 * {
 *     selected: false, // 是否是选中项
 *     baseScreen: true, // 是否是基础分屏，不开启异形屏时，这个字段作为区分标准。
 *     showInToolbar: true, // 是否展示在工具栏中
 *     id: 'a1', // 唯一索引
 *     title: '1分屏', // 分屏标题
 *     icon: '1X1', // svg-icon中图标名称
 *     iconBackup: '1X1', // svg-icon中图标名称用户工具栏图标显示
 *     fontSize: 1.18,
 *     screenNum: 1, // 分屏下实际数量
 *     group: 'average', // 分组 平均 average 高亮分割 highlight 水平 horizontal 垂直 vertical 其他 other
 *     component: 'average_1', // 对应分屏模板组件名称，命名规则 类别 + 分屏信息
 * }
 */
export const SCREENS = [
    {
        selected: false,
        baseScreen: true,
        showInToolbar: true,
        id: 'a1',
        title: '1分屏',
        icon: 'a1',
        iconBackup: '1X1',
        fontSize: 1.18,
        screenNum: 1,
        group: 'average',
        component: 'average_x',
    },
    {
        selected: false,
        baseScreen: true,
        showInToolbar: true,
        id: 'a4',
        title: '4分屏',
        icon: 'a4',
        iconBackup: '4X4',
        fontSize: 1.2,
        screenNum: 4,
        group: 'average',
        component: 'average_x',
    },
    {
        selected: false,
        baseScreen: true,
        showInToolbar: true,
        id: 'a9',
        title: '9分屏',
        icon: 'a9',
        iconBackup: '9X9',
        fontSize: 1.2,
        screenNum: 9,
        group: 'average',
        component: 'average_x',
    },
    {
        selected: false,
        baseScreen: true,
        showInToolbar: true,
        id: 'a16',
        title: '16分屏',
        icon: 'a16',
        iconBackup: '16X16',
        fontSize: 1.2,
        screenNum: 16,
        group: 'average',
        component: 'average_x',
    },
    {
        selected: false,
        baseScreen: true,
        showInToolbar: true,
        id: 'a25',
        title: '25分屏',
        icon: 'a25',
        iconBackup: '25X25',
        fontSize: 1.2,
        screenNum: 25,
        group: 'average',
        component: 'average_x',
    },
    {
        selected: false,
        id: 'hl15',
        title: '高亮分割1+5分屏',
        icon: 'hl15',
        fontSize: 1.2,
        screenNum: 6,
        group: 'highlight',
        component: 'highlight_1_5',
    },
    {
        selected: false,
        id: 'hl17',
        title: '高亮分割1+7分屏',
        icon: 'hl17',
        fontSize: 1.2,
        screenNum: 8,
        group: 'highlight',
        component: 'highlight_1_7',
    },
    {
        selected: false,
        id: 'hl18',
        title: '高亮分割1+8分屏',
        icon: 'hl18',
        fontSize: 1.2,
        screenNum: 9,
        group: 'highlight',
        component: 'highlight_1_8',
    },
    {
        selected: false,
        id: 'hl19',
        title: '高亮分割1+9分屏',
        icon: 'hl19',
        fontSize: 1.2,
        screenNum: 10,
        group: 'highlight',
        component: 'highlight_1_9',
    },
    {
        selected: false,
        id: 'hl111',
        title: '高亮分割1+11分屏',
        icon: 'hl111',
        fontSize: 1.2,
        screenNum: 12,
        group: 'highlight',
        component: 'highlight_1_11',
    },
    {
        selected: false,
        id: 'hl115',
        title: '高亮分割1+15分屏',
        icon: 'hl115',
        fontSize: 1.2,
        screenNum: 16,
        group: 'highlight',
        component: 'highlight_1_15',
    },
    {
        selected: false,
        id: 'hl116',
        title: '高亮分割1+16分屏',
        icon: 'hl116',
        fontSize: 1.2,
        screenNum: 17,
        group: 'highlight',
        component: 'highlight_1_16',
    },
    {
        selected: false,
        id: 'h1x2',
        title: '水平1*2分屏',
        icon: 'h1x2',
        fontSize: 1.2,
        screenNum: 2,
        group: 'horizontal',
        component: 'horizontal_1_2_multiply',
    },
    {
        selected: false,
        id: 'h12',
        title: '水平1+2分屏',
        icon: 'h12',
        fontSize: 1.2,
        screenNum: 3,
        group: 'horizontal',
        component: 'horizontal_1_2',
    },
    {
        selected: false,
        id: 'h14',
        title: '水平1+4分屏',
        icon: 'h14',
        fontSize: 1.2,
        screenNum: 5,
        group: 'horizontal',
        component: 'horizontal_1_4',
    },
    {
        selected: false,
        id: 'h2x3',
        title: '水平2*3分屏',
        icon: 'h2x3',
        fontSize: 1.2,
        screenNum: 6,
        group: 'horizontal',
        component: 'horizontal_2_3_multiply',
    },
    {
        selected: false,
        id: 'h2x4',
        title: '水平2*4分屏',
        icon: 'h2x4',
        fontSize: 1.2,
        screenNum: 8,
        group: 'horizontal',
        component: 'horizontal_2_4_multiply',
    },
    {
        selected: false,
        id: 'v2x1',
        title: '垂直2*1分屏',
        icon: 'v2x1',
        fontSize: 1.2,
        screenNum: 2,
        group: 'vertical',
        component: 'vertical_2_1_multiply',
    },
    {
        selected: false,
        id: 'v21',
        title: '垂直2+1分屏',
        icon: 'v21',
        fontSize: 1.2,
        screenNum: 3,
        group: 'vertical',
        component: 'vertical_2_1',
    },
    {
        selected: false,
        id: 'v41',
        title: '垂直4+1分屏',
        icon: 'v41',
        fontSize: 1.2,
        screenNum: 5,
        group: 'vertical',
        component: 'vertical_4_1',
    },
    {
        selected: false,
        id: 'v3x2',
        title: '垂直3*2分屏',
        icon: 'v3x2',
        fontSize: 1.2,
        screenNum: 6,
        group: 'vertical',
        component: 'vertical_3_2_multiply',
    },
    {
        selected: false,
        id: 'v4x2',
        title: '垂直4*2分屏',
        icon: 'v4x2',
        fontSize: 1.2,
        screenNum: 8,
        group: 'vertical',
        component: 'vertical_4_2_multiply',
    },
    {
        selected: false,
        id: 'o13',
        title: '其他1+3分屏',
        icon: 'o13',
        fontSize: 1.2,
        screenNum: 4,
        group: 'other',
        component: 'other_1_3',
    },
    {
        selected: false,
        id: 'o31',
        title: '其他3+1分屏',
        icon: 'o31',
        fontSize: 1.2,
        screenNum: 4,
        group: 'other',
        component: 'other_3_1',
    },
    {
        selected: false,
        id: 'o14',
        title: '其他1+4分屏',
        icon: 'o14',
        fontSize: 1.2,
        screenNum: 5,
        group: 'other',
        component: 'other_1_4',
    },
    {
        selected: false,
        id: 'o24',
        title: '其他2+4分屏',
        icon: 'o24',
        fontSize: 1.2,
        screenNum: 6,
        group: 'other',
        component: 'other_2_4',
    },
    {
        selected: false,
        id: 'o34',
        title: '其他3+4分屏',
        icon: 'o34',
        fontSize: 1.2,
        screenNum: 7,
        group: 'other',
        component: 'other_3_4',
    },
    {
        selected: false,
        id: 'o43',
        title: '其他4+3分屏',
        icon: 'o43',
        fontSize: 1.2,
        screenNum: 7,
        group: 'other',
        component: 'other_4_3',
    },
    {
        selected: false,
        id: 'o4x3',
        title: '其他4*3分屏',
        icon: 'o4x3',
        fontSize: 1.2,
        screenNum: 12,
        group: 'other',
        component: 'other_4_3_multiply',
    },
    {
        selected: false,
        id: 'o112',
        title: '其他1+12分屏',
        icon: 'o112',
        fontSize: 1.2,
        screenNum: 13,
        group: 'other',
        component: 'other_1_12',
    },
];
